import type { Metadata } from "next";
import "@styles/globals.css";
import AuthRouter from "@/components/auth-router";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AuthRouter>{children}</AuthRouter>
      </body>
    </html>
  );
}
